/* ============================================================
   英雄科普数据（js/data.js）
   ------------------------------------------------------------
   字段说明：
   - key    ：英文标识（唯一，供逻辑使用）
   - name   ：中文名
   - en     ：英文全名
   - cls    ：职业分类（cosmic/tech/mutant/skill/science/mystic）
   - stars  ：参考星级（1-6，仅作科普示意，实际随版本变化）
   - desc   ：一句话科普 / 定位说明
   - img    ：英雄立绘（来自漫威超级争霸战官网）
   - link   ：英雄简介页链接（跳转到官网 spotlight 页面）

   说明：以下 180 位英雄共 6 大职业、每职业 30 位，
   名称 / 立绘 / 简介链接均取自漫威超级争霸战官网。
   ============================================================ */

/* 职业中文名映射（供图鉴标签与筛选使用） */
const CLASS_NAMES = {
  cosmic: "宇宙",
  tech: "科技",
  mutant: "变异",
  skill: "格斗",
  science: "科学",
  mystic: "神秘"
};

/* 英雄数据集（共 180 位，六大职业各 30 位） */
const CHAMPIONS = [
  /* ==================== 宇宙系 Cosmic（30） ==================== */
  { key: "captainmarvel", name: "惊奇队长", en: "Captain Marvel", cls: "cosmic", stars: 5,
    desc: "卡罗尔·丹弗斯。双星能量姿态切换，攻守兼备，是宇宙系主力打手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-captain-marvel-mcu-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-captain-marvel/" },
  { key: "thanos", name: "灭霸", en: "Thanos", cls: "cosmic", stars: 6,
    desc: "宇宙霸主，无限手套带来毁灭性爆发，顶级爆发与生存并存。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-thanos-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-thanos/" },
  { key: "thor", name: "雷神托尔", en: "Thor", cls: "cosmic", stars: 5,
    desc: "阿斯加德雷神，雷霆连段爆发高，能造成多段真实伤害。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-thor-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-thor/" },
  { key: "silversurfer", name: "银影侠", en: "Silver Surfer", cls: "cosmic", stars: 5,
    desc: "冲浪于星际的信使，能量护盾坚韧，增益叠加越打越强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-silver-surfer-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-silver-surfer/" },
  { key: "venom", name: "毒液", en: "Venom", cls: "cosmic", stars: 5,
    desc: "共生体宿主，吞噬增减免益并回血，近战压制力强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-venom-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-venom/" },
  { key: "groot", name: "格鲁特", en: "Groot", cls: "cosmic", stars: 4,
    desc: "树人守卫，自愈与净化并存，是团队可靠的续航与控场。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-groot-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-groot/" },
  { key: "gamora", name: "卡魔拉", en: "Gamora", cls: "cosmic", stars: 5,
    desc: "银河护卫队刺客，连击叠加流血，输出随连段稳步攀升。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-gamora-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-gamora/" },
  { key: "drax", name: "德拉克斯", en: "Drax", cls: "cosmic", stars: 4,
    desc: "毁灭者德拉克斯，怒气强化重击，简单粗暴的近战输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-drax-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-drax/" },
  { key: "nova", name: "诺瓦", en: "Nova", cls: "cosmic", stars: 5,
    desc: "新星军团之力，能量护盾与轰炸兼备，机动性强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-nova-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nova/" },
  { key: "adamwarlock", name: "亚当·术士", en: "Adam Warlock", cls: "cosmic", stars: 6,
    desc: "宇宙级存在，复活与伤害叠加机制强大，上限极高。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-adam-warlock-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-adam-warlock/" },
  { key: "hercules", name: "海格力斯", en: "Hercules", cls: "cosmic", stars: 6,
    desc: "希腊大力神，越战越勇的狂暴输出，可叠加超多增益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hercules-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hercules/" },
  { key: "hela", name: "海拉", en: "Hela", cls: "cosmic", stars: 5,
    desc: "死亡女神，复活与死亡机制的收割者，控场能力强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hela-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hela/" },
  { key: "heimdall", name: "海姆达尔", en: "Heimdall", cls: "cosmic", stars: 4,
    desc: "阿斯加德守望者，全视之眼洞察对手，反击精准。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-heimdall-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-heimdall/" },
  { key: "angela", name: "安吉拉", en: "Angela", cls: "cosmic", stars: 5,
    desc: "天使族战士，神圣增益常驻，治疗驱逐兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-angela-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-angela/" },
  { key: "betaraybill", name: "贝塔雷·比尔", en: "Beta Ray Bill", cls: "cosmic", stars: 5,
    desc: "持有风暴锤的异星战士，雷霆输出与格挡反击兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-beta-ray-bill-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-beta-ray-bill/" },
  { key: "blackbolt", name: "黑蝠王", en: "Black Bolt", cls: "cosmic", stars: 5,
    desc: "异人族之王，音波震荡毁灭性十足，爆发输出核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-black-bolt-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-black-bolt/" },
  { key: "medusa", name: "美杜莎", en: "Medusa", cls: "cosmic", stars: 5,
    desc: "异人族女王，发丝如刃叠加强化，输出与控场并重。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-medusa-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-medusa/" },
  { key: "hyperion", name: "亥伯龙", en: "Hyperion", cls: "cosmic", stars: 5,
    desc: "永恒族强者，能量充沛爆发极高，是宇宙系爆发担当。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hyperion-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hyperion/" },
  { key: "phoenix", name: "凤凰女", en: "Phoenix", cls: "cosmic", stars: 5,
    desc: "凤凰之力宿主，死亡烙印与再生兼备，输出持续恐怖。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-phoenix-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-phoenix/" },
  { key: "gorr", name: "屠神者格尔", en: "Gorr the God Butcher", cls: "cosmic", stars: 6,
    desc: "屠神之刃，对神明类英雄克制明显，爆发与吸血兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-gorr-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-gorr-the-god-butcher/" },
  { key: "knull", name: "纳尔", en: "Knull", cls: "cosmic", stars: 6,
    desc: "共生体之神，暗黑减益与召唤协同，压制能力极强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-knull-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-knull/" },
  { key: "odin", name: "奥丁", en: "Odin", cls: "cosmic", stars: 6,
    desc: "阿斯加德众神之父，全能力加持队友，团队增益核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-odin-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-odin/" },
  { key: "cullobsidian", name: "黑矮星", en: "Cull Obsidian", cls: "cosmic", stars: 5,
    desc: "灭霸黑曜五将之一，重甲破盾，格挡与反击具破坏力。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-cull-obsidian-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-cull-obsidian/" },
  { key: "corvusglaive", name: "亡刃将军", en: "Corvus Glaive", cls: "cosmic", stars: 5,
    desc: "黑曜五将之首，任务标记叠加爆发，收割节奏凌厉。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-corvus-glaive-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-corvus-glaive/" },
  { key: "proximamidnight", name: "暗夜比邻星", en: "Proxima Midnight", cls: "cosmic", stars: 5,
    desc: "黑曜五将之一，长矛连段精准，闪避反击输出可观。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-proxima-midnight-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-proxima-midnight/" },
  { key: "ronan", name: "罗南", en: "Ronan", cls: "cosmic", stars: 4,
    desc: "克里族指控者，审判锤眩晕控场，克制增减免益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ronan-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ronan/" },
  { key: "annihilus", name: "歼灭者", en: "Annihilus", cls: "cosmic", stars: 5,
    desc: "负空间霸主，宇宙权杖增益强化，攻防两端扎实。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-annihilus-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-annihilus/" },
  { key: "ikaris", name: "伊卡里斯", en: "Ikaris", cls: "cosmic", stars: 5,
    desc: "永恒族强者，能量射线连击，飞行姿态机动性强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ikaris-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ikaris/" },
  { key: "msmarvel", name: "惊奇女士", en: "Ms. Marvel", cls: "cosmic", stars: 5,
    desc: "卡玛拉·汗，弹性变形连段，控制与输出皆有亮点。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ms-marvel-kamala-khan-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ms-marvel-kamala-khan/" },
  { key: "cosmicghostrider", name: "宇宙恶灵骑士", en: "Cosmic Ghost Rider", cls: "cosmic", stars: 5,
    desc: "惩罚者与恶灵骑士的合体，火焰连段与再生兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-cosmic-ghost-rider-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-cosmic-ghost-rider/" },

  /* ==================== 科技系 Tech（30） ==================== */
  { key: "ironman", name: "钢铁侠", en: "Iron Man", cls: "tech", stars: 5,
    desc: "托尼·斯塔克。高爆发远程输出，装甲附带能量护盾，适合主攻与破防。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-iron-man-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-iron-man/" },
  { key: "starlord", name: "星爵", en: "Star-Lord", cls: "tech", stars: 5,
    desc: "彼得·奎尔，元素炮连段叠加，科技系高爆发输出手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-star-lord-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-star-lord/" },
  { key: "rocketraccoon", name: "火箭浣熊", en: "Rocket Raccoon", cls: "tech", stars: 4,
    desc: "银河护卫队军械师，重火力连段爆发，减益易伤兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-rocket-raccoon-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-rocket-raccoon/" },
  { key: "nebula", name: "星云", en: "Nebula", cls: "tech", stars: 5,
    desc: "改造体战士，能量充能与放电循环，输出与控场并重。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-nebula-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nebula/" },
  { key: "ultron", name: "奥创", en: "Ultron", cls: "tech", stars: 6,
    desc: "人工智能反派，能量吸收与自我修复，科技系全面型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ultron-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ultron/" },
  { key: "warmachine", name: "战争机器", en: "War Machine", cls: "tech", stars: 4,
    desc: "詹姆斯·罗德斯上校，重机枪扫射附带燃烧，减益压制。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-war-machine-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-war-machine/" },
  { key: "doctoroctopus", name: "章鱼博士", en: "Doctor Octopus", cls: "tech", stars: 5,
    desc: "机械臂操控，破甲与能量控制兼备，克制增减免益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-doctor-octopus-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-doctor-octopus/" },
  { key: "greengoblin", name: "绿魔", en: "Green Goblin", cls: "tech", stars: 5,
    desc: "诺曼·奥斯本，滑翔炸弹与毒素减益，远程消耗出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-green-goblin-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-green-goblin/" },
  { key: "hulkbuster", name: "反浩克装甲", en: "Hulkbuster", cls: "tech", stars: 5,
    desc: "专克巨力型对手的重甲，格挡反击与减益护盾兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hulkbuster-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hulkbuster/" },
  { key: "vision", name: "幻视", en: "Vision", cls: "tech", stars: 5,
    desc: "振金合成体，能量汲取与增益护盾，克制能量型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-vision-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-vision/" },
  { key: "sentinel", name: "哨兵机器人", en: "Sentinel", cls: "tech", stars: 5,
    desc: "变种人猎手，分析叠加递增输出，持久战越打越强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-sentinel-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-sentinel/" },
  { key: "mysterio", name: "神秘客", en: "Mysterio", cls: "tech", stars: 4,
    desc: "幻象克敌，毒雾气体致盲减益，控制与迷惑对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mysterio-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mysterio/" },
  { key: "vulture", name: "秃鹫", en: "Vulture", cls: "tech", stars: 4,
    desc: "机械翼突袭，穿刺减益叠加强化，机动性出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-vulture-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-vulture/" },
  { key: "ghost", name: "幽灵", en: "Ghost", cls: "tech", stars: 5,
    desc: "相位穿梭，隐身与减益施加，闪避反击型科技位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ghost-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ghost/" },
  { key: "kang", name: "康", en: "Kang the Conqueror", cls: "tech", stars: 6,
    desc: "时间征服者，时间能量操控，减益与爆发输出兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2021/11/champion-kang-360x360.jpg",
    link: "https://playcontestofchampions.com/news/champion-spotlight-kang/" },
  { key: "ironpatriot", name: "钢铁爱国者", en: "Iron Patriot", cls: "tech", stars: 4,
    desc: "重装指挥者，破甲与能量护盾，节奏扎实的科技战士。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-iron-patriot-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-iron-patriot/" },
  { key: "civilwarrior", name: "内战战士", en: "Civil Warrior", cls: "tech", stars: 5,
    desc: "美队与钢铁侠的融合体，护盾与激光兼备，攻守均衡。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-civil-warrior-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-civil-warrior/" },
  { key: "spidermanstark", name: "蜘蛛侠·史塔克", en: "Spider-Man (Stark Enhanced)", cls: "tech", stars: 5,
    desc: "托尼之作蜘蛛装甲，能量脉冲连击，闪避与爆发兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-spider-man-stark-enhanced-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-spider-man-stark-enhanced/" },
  { key: "ironheart", name: "钢铁之心", en: "Ironheart", cls: "tech", stars: 5,
    desc: "莉莉·威廉姆斯，自研装甲，输出成长型科技新星。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ironheart-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ironheart/" },
  { key: "shuri", name: "苏睿", en: "Shuri", cls: "tech", stars: 5,
    desc: "瓦坎达公主，科技格斗兼备，减速减益与连击输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-shuri-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-shuri/" },
  { key: "redskull", name: "红骷髅", en: "Red Skull", cls: "tech", stars: 4,
    desc: "九头蛇首领，减益反射与重甲护盾，消耗能力出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-red-skull-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-red-skull/" },
  { key: "howardtheduck", name: "霍华德鸭", en: "Howard The Duck", cls: "tech", stars: 4,
    desc: "反英雄鸭，重火力与幽默机制，出其不意的科技手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-howard-the-duck-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-howard-the-duck/" },
  { key: "yondu", name: "勇度", en: "Yondu", cls: "tech", stars: 5,
    desc: "吹口哨控制亚卡箭，精准多段打击，克制闪避型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-yondu-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-yondu/" },
  { key: "punisher2099", name: "惩罚者2099", en: "Punisher 2099", cls: "tech", stars: 4,
    desc: "未来世界执法者，重火力扫射，减益与爆发兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-punisher-2099-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-punisher-2099/" },
  { key: "prowler", name: "徘徊者", en: "Prowler", cls: "tech", stars: 5,
    desc: "高科技爪刃，破甲与流血兼备，节奏凌厉的刺客。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-prowler-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-prowler/" },
  { key: "peniparker", name: "佩妮·帕克", en: "Peni Parker", cls: "tech", stars: 4,
    desc: "SP//dr 蜘蛛机甲，能量护盾与激光，减益抗性强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-peni-parker-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-peni-parker/" },
  { key: "omegasentinel", name: "欧米茄哨兵", en: "Omega Sentinel", cls: "tech", stars: 5,
    desc: "高级哨兵改造体，扫描叠加输出，持久战成长型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-omega-sentinel-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-omega-sentinel/" },
  { key: "warlock", name: "沃洛克", en: "Warlock", cls: "tech", stars: 5,
    desc: "技术有机体，感染减益与能量吸收，压制能力强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-warlock-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-warlock/" },
  { key: "ladydeathstrike", name: "死亡女", en: "Lady Deathstrike", cls: "tech", stars: 4,
    desc: "生化改造爪刃，流血减益叠加，克制再生型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-lady-deathstrike-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-lady-deathstrike/" },
  { key: "nimrod", name: "尼姆罗德", en: "Nimrod", cls: "tech", stars: 6,
    desc: "终极哨兵，适应战斗叠加强化，变种人克星。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-nimrod-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nimrod/" },

  /* ==================== 变异系 Mutant（30） ==================== */
  { key: "wolverine", name: "金刚狼", en: "Wolverine", cls: "mutant", stars: 6,
    desc: "超强自愈能力，狼爪撕裂附带流血，持久战之王。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wolverine-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-wolverine/" },
  { key: "magneto", name: "万磁王", en: "Magneto", cls: "mutant", stars: 5,
    desc: "掌控磁场，对金属系英雄克制明显，控制与爆发兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-magneto-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-magneto/" },
  { key: "storm", name: "暴风女", en: "Storm", cls: "mutant", stars: 5,
    desc: "操控雷电与风暴，范围伤害出色，团队能量输出核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-storm-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-storm/" },
  { key: "cyclops", name: "独眼龙", en: "Cyclops", cls: "mutant", stars: 4,
    desc: "镭射眼睛持续输出，破甲与减益叠加，团队辅助佳。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2021/11/champion-cyclops-360x360.jpg",
    link: "https://playcontestofchampions.com/news/champion-spotlight-cyclops-new-xavier-school/" },
  { key: "jeangrey", name: "琴·格蕾", en: "Jean Grey", cls: "mutant", stars: 6,
    desc: "凤凰宿主，心灵能量控场与再生兼备，上限极高。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2025/02/Champion-JeanGrey-kablog-950x950-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-jean-grey/" },
  { key: "professorx", name: "X教授", en: "Professor X", cls: "mutant", stars: 6,
    desc: "查尔斯·泽维尔，心灵感应控场，团队精神增益核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-professor-x-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-professor-x/" },
  { key: "beast", name: "野兽", en: "Beast", cls: "mutant", stars: 4,
    desc: "汉克·麦考伊，敏捷近战，突袭与流血减益兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-beast-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-beast/" },
  { key: "colossus", name: "钢力士", en: "Colossus", cls: "mutant", stars: 5,
    desc: "金属化坚不可摧，重甲格挡，近战硬碰硬的坦克。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-colossus-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-colossus/" },
  { key: "gambit", name: "牌皇", en: "Gambit", cls: "mutant", stars: 5,
    desc: "雷米·勒博，扑克牌充能爆炸，能量输出连段出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-gambit-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-gambit/" },
  { key: "rogue", name: "罗刹女", en: "Rogue", cls: "mutant", stars: 5,
    desc: "吸取能力增强自身，回血与减益复制，续航出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-rogue-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-rogue/" },
  { key: "nightcrawler", name: "夜行者", en: "Nightcrawler", cls: "mutant", stars: 4,
    desc: "瞬间传送闪避，多段突袭，机动性极强的近战刺客。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-nightcrawler-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nightcrawler/" },
  { key: "iceman", name: "冰人", en: "Iceman", cls: "mutant", stars: 5,
    desc: "波比·德雷克，冰霜减益与护盾，控场与生存兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-iceman-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-iceman/" },
  { key: "deadpool", name: "死侍", en: "Deadpool", cls: "mutant", stars: 5,
    desc: "韦德·威尔逊，自愈与近战连击兼备，幽默又实用。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-deadpool-classic-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-deadpool/" },
  { key: "cable", name: "电索", en: "Cable", cls: "mutant", stars: 6,
    desc: "内森·萨默斯，未来科技与心灵能量，远程输出核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2026/07/Champion-Cable-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-cable/" },
  { key: "domino", name: "多米诺", en: "Domino", cls: "mutant", stars: 5,
    desc: "幸运之力加持，闪避与暴击兼备，攻守灵动。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-domino-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-domino/" },
  { key: "psylocke", name: "灵蝶", en: "Psylocke", cls: "mutant", stars: 4,
    desc: "忍术与精神之刃，流血减益连段，近战输出精准。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-psylocke-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-psylocke/" },
  { key: "emmafrost", name: "白皇后", en: "Emma Frost", cls: "mutant", stars: 5,
    desc: "艾玛·弗罗斯特，钻石形态抗伤，心灵控制位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-emma-frost-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-emma-frost/" },
  { key: "sabretooth", name: "剑齿虎", en: "Sabretooth", cls: "mutant", stars: 5,
    desc: "维克多·克里德，狂暴自愈与流血连段，压制型打手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-sabretooth-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-sabretooth/" },
  { key: "archangel", name: "大天使", en: "Archangel", cls: "mutant", stars: 5,
    desc: "金属羽翼，中毒与流血减益叠加，远程压制出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-archangel-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-archangel/" },
  { key: "apocalypse", name: "天启", en: "Apocalypse", cls: "mutant", stars: 6,
    desc: "首位变种人，强化队友变种系，团队核心与重炮手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-apocalypse-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-apocalypse/" },
  { key: "jubilee", name: "朱比利", en: "Jubilee", cls: "mutant", stars: 4,
    desc: "烟花能量弹消耗，眩晕控场，灵活的中远程输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-jubilee-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-jubilee/" },
  { key: "bishop", name: "毕肖普", en: "Bishop", cls: "mutant", stars: 5,
    desc: "能量吸收再释放，减益克星，反击输出能力强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-bishop-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-bishop/" },
  { key: "kittypryde", name: "幻影猫", en: "Kitty Pryde", cls: "mutant", stars: 5,
    desc: "相位穿梭减免伤害，闪避与突袭兼备，生存极强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-kitty-pryde-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-kitty-pryde/" },
  { key: "omegared", name: "欧米茄红", en: "Omega Red", cls: "mutant", stars: 5,
    desc: "死亡孢子持续伤害，减益叠加，压制型持久战手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-omega-red-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-omega-red/" },
  { key: "mistersinister", name: "邪恶先生", en: "Mister Sinister", cls: "mutant", stars: 5,
    desc: "基因操控与分解复制，减益控制能力出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mister-sinister-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mister-sinister/" },
  { key: "havok", name: "浩劫", en: "Havok", cls: "mutant", stars: 5,
    desc: "亚历克斯·萨默斯，等离子爆发，能量输出核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-havok-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-havok/" },
  { key: "namor", name: "纳摩", en: "Namor", cls: "mutant", stars: 5,
    desc: "海底之王，水属性减益与狂怒兼备，反击型战士。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-namor-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-namor/" },
  { key: "oldmanlogan", name: "老罗根", en: "Old Man Logan", cls: "mutant", stars: 5,
    desc: "暮年金刚狼，狂怒连段爆发，减益叠加输出强劲。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wolverine-old-man-logan-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-old-man-logan/" },
  { key: "x23", name: "X-23", en: "X-23", cls: "mutant", stars: 5,
    desc: "劳拉·金妮，咧嘴爪流血连段，高机动近战刺客。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wolverine-x23-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-wolverine-x-23/" },
  { key: "sunspot", name: "太阳黑子", en: "Sunspot", cls: "mutant", stars: 4,
    desc: "罗伯托·达科斯塔，炎阳之力越烧越强，输出成长型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-sunspot-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-sunspot/" },

  /* ==================== 格斗系 Skill（30） ==================== */
  { key: "blackwidow", name: "黑寡妇", en: "Black Widow", cls: "skill", stars: 4,
    desc: "娜塔莎·罗曼诺夫，精准致残与闪避反击，削弱对手防御。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-black-widow-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-black-widow/" },
  { key: "blackpanther", name: "黑豹", en: "Black Panther", cls: "skill", stars: 5,
    desc: "瓦坎达之王，快速多段连击叠加流血，越打越快。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-black-panther-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-black-panther/" },
  { key: "hawkeye", name: "鹰眼", en: "Hawkeye", cls: "skill", stars: 4,
    desc: "克林特·巴顿，远程弓箭精准，流血与控制兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hawkeye-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hawkeye/" },
  { key: "falcon", name: "猎鹰", en: "Falcon", cls: "skill", stars: 4,
    desc: "山姆·威尔逊，空战翱翔，减益与扫射压制兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-falcon-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-falcon/" },
  { key: "wintersoldier", name: "冬日战士", en: "Winter Soldier", cls: "skill", stars: 4,
    desc: "巴基·巴恩斯，机械臂突袭，破甲连段输出扎实。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-winter-soldier-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-winter-soldier/" },
  { key: "nickfury", name: "尼克·弗瑞", en: "Nick Fury", cls: "skill", stars: 6,
    desc: "神盾局局长，战术协同与复活机制，团队增益核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-nick-fury-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nick-fury/" },
  { key: "daredevil", name: "夜魔侠", en: "Daredevil", cls: "skill", stars: 5,
    desc: "马特·默多克，超感官闪避反击，近战节奏凌厉。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-daredevil-classic-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-daredevil-classic/" },
  { key: "moonknight", name: "月光骑士", en: "Moon Knight", cls: "skill", stars: 5,
    desc: "月亮加持阶段变换，流血减益与闪避兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-moon-knight-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-moon-knight/" },
  { key: "punisher", name: "惩罚者", en: "Punisher", cls: "skill", stars: 4,
    desc: "弗兰克·卡斯特，重火力扫射，减益与爆发兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-punisher-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-punisher/" },
  { key: "elektra", name: "艾丽卡", en: "Elektra", cls: "skill", stars: 4,
    desc: "忍者刺客，双刃流血连段，克制虚弱减益目标。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-elektra-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-elektra/" },
  { key: "blade", name: "刀锋战士", en: "Blade", cls: "skill", stars: 6,
    desc: "吸血鬼猎手，对神秘/黑暗系克制明显，流血压制。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-blade-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-blade/" },
  { key: "shangchi", name: "尚气", en: "Shang-Chi", cls: "skill", stars: 6,
    desc: "功夫大师，连段节奏切换增益，近战输出核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-shang-chi-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-shang-chi/" },
  { key: "taskmaster", name: "模仿大师", en: "Taskmaster", cls: "skill", stars: 5,
    desc: "复制对手技能，减益抵抗出众，克制重复套路。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-taskmaster-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-taskmaster/" },
  { key: "crossbones", name: "交叉骨", en: "Crossbones", cls: "skill", stars: 5,
    desc: "布鲁克·朗姆洛，破甲与流血压制，克制护甲减益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-crossbones-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-crossbones/" },
  { key: "killmonger", name: "基尔芒格", en: "Killmonger", cls: "skill", stars: 5,
    desc: "埃里克·斯蒂文斯，反击与流血减益，克制格挡者。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2021/11/champion-killmonger-360x360.jpg",
    link: "https://playcontestofchampions.com/news/champion-spotlight-killmonger/" },
  { key: "kraven", name: "克莱文", en: "Kraven the Hunter", cls: "skill", stars: 4,
    desc: "追踪猎人，流血与减速减益，克制机动型目标。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-kraven-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-kraven/" },
  { key: "bullseye", name: "靶眼", en: "Bullseye", cls: "skill", stars: 4,
    desc: "神准投掷，流血叠加稳定，消耗与控场兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-bullseye-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-bullseye/" },
  { key: "blackcat", name: "黑猫", en: "Black Cat", cls: "skill", stars: 5,
    desc: "费莉希亚·哈迪，幸运闪避与窃取能力，机动刺客。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-black-cat-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-black-cat/" },
  { key: "gwenpool", name: "格温普尔", en: "Gwenpool", cls: "skill", stars: 4,
    desc: "第四面墙天赋，减益抵抗与连段，出其不意。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-gwenpool-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-gwenpool/" },
  { key: "squirrelgirl", name: "松鼠女孩", en: "Squirrel Girl", cls: "skill", stars: 5,
    desc: "多琳·格林，松鼠群殴与自愈，全能型格斗位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-squirrel-girl-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-squirrel-girl/" },
  { key: "agentvenom", name: "特工毒液", en: "Agent Venom", cls: "skill", stars: 5,
    desc: "弗莱什·汤普森，共生体武器化，减益与输出兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-agent-venom-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-agent-venom/" },
  { key: "korg", name: "寇格", en: "Korg", cls: "skill", stars: 4,
    desc: "岩石战士，格挡反击减益，克制闪避型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-korg-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-korg/" },
  { key: "kingpin", name: "金并", en: "Kingpin", cls: "skill", stars: 5,
    desc: "威尔逊·菲斯克，重甲减益与增益清除，控场扎实。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-kingpin-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-kingpin/" },
  { key: "aegon", name: "艾格恩", en: "Aegon", cls: "skill", stars: 5,
    desc: "累积连击成长伤害，越砍越强，长线收割担当。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-aegon-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-aegon/" },
  { key: "ronin", name: "浪人", en: "Ronin", cls: "skill", stars: 5,
    desc: "鹰眼的浪人身份，连段切换快节奏，闪避减益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ronin-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ronin/" },
  { key: "valkyrie", name: "女武神", en: "Valkyrie", cls: "skill", stars: 5,
    desc: "阿斯加德女武神，突袭连段，克制减益增福对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-valkyrie-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-valkyrie/" },
  { key: "mantis", name: "螳螂女", en: "Mantis", cls: "skill", stars: 4,
    desc: "读心与昏睡控场，增益辅助，团队灵活位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2022/12/champion-mantis-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mantis/" },
  { key: "katebishop", name: "凯特·毕肖普", en: "Kate Bishop", cls: "skill", stars: 5,
    desc: "新一代鹰眼，精准箭雨连段，流血与控场兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-kate-bishop-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-kate-bishop/" },
  { key: "baronzemo", name: "泽莫男爵", en: "Baron Zemo", cls: "skill", stars: 4,
    desc: "海因里希·泽莫，毒剂减益与破甲，克制增益对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-baron-zemo-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-baron-zemo/" },
  { key: "hitmonkey", name: "猴子杀手", en: "Hit-Monkey", cls: "skill", stars: 5,
    desc: "热血杀手猴，狂怒连段爆发，减益与输出兼具。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hit-monkey-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hit-monkey/" },

  /* ==================== 科学系 Science（30） ==================== */
  { key: "captainamerica", name: "美国队长", en: "Captain America", cls: "science", stars: 5,
    desc: "史蒂夫·罗杰斯，盾牌格挡稳如堡垒，眩晕控制强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-captain-america-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-captain-america/" },
  { key: "hulk", name: "绿巨人浩克", en: "Hulk", cls: "science", stars: 5,
    desc: "布鲁斯·班纳，怒气累积越战越勇，越残血越恐怖。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-hulk-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-hulk/" },
  { key: "spiderman", name: "蜘蛛侠", en: "Spider-Man", cls: "science", stars: 4,
    desc: "彼得·帕克，高闪避与易伤施加，机动性极强的拉扯。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2014/11/champion-classic-spider-man-360x360.jpg",
    link: "https://playcontestofchampions.com/news/champion-spotlight-spider-man-classic/" },
  { key: "antman", name: "蚁人", en: "Ant-Man", cls: "science", stars: 4,
    desc: "斯科特·朗，缩小连段节奏奇快，附加强力减速。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ant-man-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ant-man/" },
  { key: "wasp", name: "黄蜂女", en: "Wasp", cls: "science", stars: 4,
    desc: "霍普·凡·戴恩，高射击连段，破甲叠加核心输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wasp-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-wasp/" },
  { key: "thing", name: "石头人", en: "Thing", cls: "science", stars: 5,
    desc: "本·格林，岩石装甲硬碰硬，格挡反击与减益抗性。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-thing-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-thing/" },
  { key: "humantorch", name: "霹雳火", en: "Human Torch", cls: "science", stars: 5,
    desc: "强尼·斯通，烈焰灼伤叠加，对格斗/变异系克制。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-human-torch-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-human-torch/" },
  { key: "invisiblewoman", name: "隐形女", en: "Invisible Woman", cls: "science", stars: 5,
    desc: "苏珊·斯通，力场护盾与隐形，攻守兼备的团队位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-invisible-woman-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-invisible-woman/" },
  { key: "misterfantastic", name: "神奇先生", en: "Mister Fantastic", cls: "science", stars: 5,
    desc: "里德·理查兹，弹性连段与减益吸收，控场与输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mister-fantastic-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mister-fantastic/" },
  { key: "redhulk", name: "红浩克", en: "Red Hulk", cls: "science", stars: 5,
    desc: "罗斯将军，灼热怒气叠加，减益吸收强化输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-red-hulk-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-red-hulk/" },
  { key: "shehulk", name: "女浩克", en: "She-Hulk", cls: "science", stars: 5,
    desc: "詹妮弗·沃尔特斯，狂怒与眩晕兼备，节奏灵活。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-she-hulk-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-she-hulk/" },
  { key: "lukecage", name: "卢克·凯奇", en: "Luke Cage", cls: "science", stars: 4,
    desc: "刀枪不入的坚盾，格挡反弹，近战坦克型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-luke-cage-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-luke-cage/" },
  { key: "jessicajones", name: "杰西卡·琼斯", en: "Jessica Jones", cls: "science", stars: 4,
    desc: "私家侦探，怪力与破甲，克制增益型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-jessica-jones-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-jessica-jones/" },
  { key: "sentry", name: "哨兵", en: "Sentry", cls: "science", stars: 6,
    desc: "拥有百万吨之力，怒气爆发极高，科学系重炮。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-sentry-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-sentry/" },
  { key: "electro", name: "电光人", en: "Electro", cls: "science", stars: 4,
    desc: "马克斯·狄龙，静电反伤，克制连击近战型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-electro-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-electro/" },
  { key: "rhino", name: "犀牛人", en: "Rhino", cls: "science", stars: 4,
    desc: "阿列克谢·斯特列休克，重甲冲撞，减益抗性强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-rhino-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-rhino/" },
  { key: "sandman", name: "沙人", en: "Sandman", cls: "science", stars: 4,
    desc: "弗林特·马尔科，沙化再生减伤，控场与生存兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-sandman-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-sandman/" },
  { key: "scorpion", name: "蝎子", en: "Scorpion", cls: "science", stars: 4,
    desc: "麦克·加根，毒尾连段眩晕，控制与输出兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-scorpion-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-scorpion/" },
  { key: "quicksilver", name: "快银", en: "Quicksilver", cls: "science", stars: 5,
    desc: "皮特罗·马克西莫夫，极速连段，减益叠加节奏极快。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-quicksilver-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-quicksilver/" },
  { key: "modok", name: "魔多客", en: "M.O.D.O.K.", cls: "science", stars: 5,
    desc: "智力改造巨脑，能量护盾与远程压制，控制出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-modok-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-m-o-d-o-k/" },
  { key: "abomination", name: "憎恶", en: "Abomination", cls: "science", stars: 5,
    desc: "埃米尔·布朗斯基，毒气减益与怪力，近战输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-abomination-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-abomination/" },
  { key: "spidergwen", name: "蜘蛛格温", en: "Spider-Gwen", cls: "science", stars: 5,
    desc: "格温·斯黛西，蛛丝控场与闪避，节制对手节奏。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-spider-gwen-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-spider-gwen/" },
  { key: "spidermanmiles", name: "蜘蛛侠·迈尔斯", en: "Spider-Man (Miles Morales)", cls: "science", stars: 5,
    desc: "迈尔斯·莫拉莱斯，电击与隐身，机动与控场兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-spider-man-miles-morales-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-spider-man-miles-morales/" },
  { key: "misternegative", name: "负先生", en: "Mister Negative", cls: "science", stars: 5,
    desc: "马丁·李，黑暗能量与减益反转，克制增益型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mister-negative-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mister-negative/" },
  { key: "yellowjacket", name: "黄衫侠", en: "Yellowjacket", cls: "science", stars: 4,
    desc: "达伦·克罗斯，缩小连击叠加，破甲与控场并重。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-yellowjacket-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-yellowjacket/" },
  { key: "quake", name: "震波女", en: "Quake", cls: "science", stars: 5,
    desc: "黛西·约翰逊，振动波连段，减益与控场能力出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-quake-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-quake/" },
  { key: "photon", name: "光子", en: "Photon", cls: "science", stars: 5,
    desc: "莫妮卡·兰博，光能连段输出，能量压制能力强。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-photon-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-photon/" },
  { key: "morbius", name: "莫比亚斯", en: "Morbius", cls: "science", stars: 5,
    desc: "活吸血鬼，吸血回血与流血减益，续航压制出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-morbius-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-morbius/" },
  { key: "spiderman2099", name: "蜘蛛侠2099", en: "Spider-Man 2099", cls: "science", stars: 5,
    desc: "米格·奥哈拉，未来科技蛛网，减速减益压制。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-spider-man-2099-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-spider-man-2099/" },
  { key: "bluemarvel", name: "蓝惊奇", en: "Blue Marvel", cls: "science", stars: 6,
    desc: "亚当·布拉希尔，反物质能量爆发，科学系重炮手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2026/01/Champion-BlueMarvel-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-blue-marvel/" },

  /* ==================== 神秘系 Mystic（30） ==================== */
  { key: "doctorstrange", name: "奇异博士", en: "Doctor Strange", cls: "mystic", stars: 6,
    desc: "至尊法师，法术多样，可治疗、反伤并堆叠奥术增益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2017/11/Champion-DrStrange-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-doctor-strange/" },
  { key: "scarletwitch", name: "猩红女巫", en: "Scarlet Witch", cls: "mystic", stars: 6,
    desc: "旺达·马克西莫夫，混沌魔法概率触发异常，爆发上限高。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-scarlet-witch-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-scarlet-witch/" },
  { key: "ghostrider", name: "恶灵骑士", en: "Ghost Rider", cls: "mystic", stars: 5,
    desc: "强尼·布雷兹，火焰与命运审判，减益与复活兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2026/05/Champion-GhostRider-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ghost-rider/" },
  { key: "doctordoom", name: "毁灭博士", en: "Doctor Doom", cls: "mystic", stars: 6,
    desc: "维克多·冯·杜姆，能量与减益控制，神秘系全能核心。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-doctor-doom-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-doctor-doom/" },
  { key: "loki", name: "洛基", en: "Loki", cls: "mystic", stars: 5,
    desc: "诡计之神，减益复制与先手优势，控制能力出众。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-loki-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-loki/" },
  { key: "magik", name: "秘客", en: "Magik", cls: "mystic", stars: 5,
    desc: "伊利亚娜·拉斯普廷，灵魂之刃，减益与能量压制。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-magik-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-magik/" },
  { key: "ironfist", name: "铁拳", en: "Iron Fist", cls: "mystic", stars: 4,
    desc: "丹尼·兰德，气功之拳，破甲连段与总伤害充沛。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-iron-fist-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-iron-fist/" },
  { key: "mephisto", name: "墨菲斯托", en: "Mephisto", cls: "mystic", stars: 6,
    desc: "地狱君主，火焰焚烧与复活，集团压制减益。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mephisto-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mephisto/" },
  { key: "dormammu", name: "多玛姆", en: "Dormammu", cls: "mystic", stars: 5,
    desc: "暗黑维度之主，能量护盾与减益，防守反击可靠。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-dormammu-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-dormammu/" },
  { key: "juggernaut", name: "红坦克", en: "Juggernaut", cls: "mystic", stars: 5,
    desc: "凯恩·马尔科，不可阻挡冲撞，格挡穿透输出高。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-juggernaut-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-juggernaut/" },
  { key: "thehood", name: "兜帽人", en: "The Hood", cls: "mystic", stars: 5,
    desc: "帕克·罗宾斯，黑暗减益与隐身，克制增减免益对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-the-hood-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-the-hood/" },
  { key: "absorbingman", name: "吸收人", en: "Absorbing Man", cls: "mystic", stars: 5,
    desc: "卡尔·克里尔，吸收属性反制对手，克制能量型。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-absorbing-man-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-absorbing-man/" },
  { key: "ebonymaw", name: "乌木喉", en: "Ebony Maw", cls: "mystic", stars: 5,
    desc: "灭霸黑曜五将之一，念力控场，减益与锁定兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-ebony-maw-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-ebony-maw/" },
  { key: "wong", name: "王", en: "Wong", cls: "mystic", stars: 5,
    desc: "至尊法师随从，法术连段与团队增益，控场可靠。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wong-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-wong/" },
  { key: "mordo", name: "莫度", en: "Mordo", cls: "mystic", stars: 4,
    desc: "卡尔·莫度，奥术反制与减益，克制法术型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-mordo-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-mordo/" },
  { key: "dracula", name: "德古拉", en: "Dracula", cls: "mystic", stars: 5,
    desc: "吸血伯爵，回血与流血减益，续航压制兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2025/10/Champion-Dracula-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-dracula/" },
  { key: "americachavez", name: "阿美莉卡·查韦斯", en: "America Chavez", cls: "mystic", stars: 5,
    desc: "跨维度星斧战士，空间穿梭连段，输出扎实。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-america-chavez-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-america-chavez/" },
  { key: "nicominoru", name: "妮可·米诺鲁", en: "Nico Minoru", cls: "mystic", stars: 5,
    desc: "魔杖少女，法术减益与团队增益，神秘系灵活位。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2025/05/Champion-NicoMinoru-kablog-960x960-1-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-nico-minoru/" },
  { key: "tigra", name: "虎女", en: "Tigra", cls: "mystic", stars: 5,
    desc: "珍妮弗·凯尔，猫科敏捷与灵魂之力，近战输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-tigra-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-tigra/" },
  { key: "dragonman", name: "龙人", en: "Dragon Man", cls: "mystic", stars: 4,
    desc: "邪恶博士的龙型造物，火焰连段与狂热输出。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-dragon-man-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-dragon-man/" },
  { key: "guillotine", name: "断头台", en: "Guillotine", cls: "mystic", stars: 4,
    desc: "断头之刃回血，减益与输出兼备，续航型打手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-guillotine-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-guillotine/" },
  { key: "enchantress", name: "魅惑女巫", en: "Enchantress", cls: "mystic", stars: 5,
    desc: "阿莫拉，魅惑与法术减益，克制增益型对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-enchantress-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-enchantress/" },
  { key: "thorjanefoster", name: "雷神·简·福斯特", en: "Thor (Jane Foster)", cls: "mystic", stars: 5,
    desc: "女雷神，雷霆连段与护盾，输出控场兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-thor-jane-foster-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-thor-jane-foster/" },
  { key: "manthing", name: "沼泽怪物", en: "Man-Thing", cls: "mystic", stars: 4,
    desc: "沼泽守卫，燃烧减益与植物控制，克制火焰连段。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-man-thing-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-man-thing/" },
  { key: "whitetiger", name: "白虎", en: "White Tiger", cls: "mystic", stars: 5,
    desc: "白虎护符加持，敏捷连段与流血减益觉醒。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-white-tiger-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-white-tiger/" },
  { key: "wiccan", name: "巫士", en: "Wiccan", cls: "mystic", stars: 5,
    desc: "比利·卡普兰，混沌魔法复制，克制减益增福对手。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-wiccan-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-wiccan/" },
  { key: "doctorvoodoo", name: "巫毒博士", en: "Doctor Voodoo", cls: "mystic", stars: 5,
    desc: "杰里科·德鲁姆，巫毒法术与治疗，控场减益兼备。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-doctor-voodoo-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-doctor-voodoo/" },
  { key: "symbiotesupreme", name: "共生体至尊", en: "Symbiote Supreme", cls: "mystic", stars: 5,
    desc: "共生体融合至尊法师，魔力强化爆发惊人。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-symbiote-supreme-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-symbiote-supreme/" },
  { key: "diablo", name: "迪亚波罗", en: "Diablo", cls: "mystic", stars: 4,
    desc: "炼金术士，药剂减益与增益，控场能力出色。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-diablo-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-diablo/" },
  { key: "werewolfbynight", name: "夜里狼人", en: "Werewolf By Night", cls: "mystic", stars: 4,
    desc: "杰克·罗素，狼人变身回血，近战爆发与续航。",
    img: "https://playcontestofchampions.com/wp-content/uploads/2023/04/champion-werewolf-by-night-360x360.webp",
    link: "https://playcontestofchampions.com/news/champion-spotlight-werewolf-by-night/" }
];